scalar Date

type Fraction {
  numerator: Int!
  denominator: Int!
}

type Location {
  id: ID!
  name: String!
}

type Category {
  id: ID!
  name: String!
  colorCode: String!
  ingredients: [Ingredient!]!
}

type Ingredient {
  id: ID!
  name: String!
  category: Category!
  inventory: [Inventory!]!
  purchaseHistory: [PurchaseHistory!]!
}

type Inventory {
  id: ID!
  ingredient: Ingredient!
  quantity: Fraction!
  unit: String!
  expiryDate: String!
  frozen: Boolean!
  expired: Boolean!
}

type PurchaseHistory {
  id: ID!
  ingredient: Ingredient!
  date: String!
  location: Location!
  price: Int!
}


input FractionInput {
  numerator: Int!
  denominator: Int!
}

input UpdateCategoryInput {
  name: String!
  colorCode: String
}

input NewLocation {
  name: String!
}

input UpdateLocationInput {
  name: String!
}

input NewCategory {
  name: String!
  colorCode: String
}

input NewIngredient {
  name: String!
  categoryId: ID!
}

input NewInventory {
  ingredientId: ID!
  quantity: FractionInput!
  unit: String!
  expiryDate: String!
  frozen: Boolean!
}

input UpdateInventory {
  quantity: FractionInput
  unit: String
  expiryDate: String
  frozen: Boolean
}

input InventoryFilter {
  ingredientId: ID
}

enum InventorySort {
  EXPIRY_ASC
  EXPIRY_DESC
}

input NewPurchaseHistory {
  ingredientId: ID!
  quantity: FractionInput!
  unit: String!
  date: String!
  locationId: ID!
  price: Int!
}

input UpdatePurchaseHistory {
  quantity: FractionInput
  unit: String
  date: String
  locationId: ID
  price: Int
}

input UpdateQuantity {
  numerator: Int!
  denominator: Int!
}

type Query {
  locations: [Location!]!
  location(id: ID!): Location
  categories: [Category!]!
  category(id: ID!): Category
  ingredients(categoryId: ID, q: String): [Ingredient!]!
  inventory(id: ID, filter: InventoryFilter, sort: InventorySort): [Inventory!]!
  purchaseHistory(ingredientId: ID): [PurchaseHistory!]!
}

type Mutation {
  createLocation(input: NewLocation!): Location!
  updateLocation(id: ID!, input: UpdateLocationInput!): Location!
  deleteLocation(id: ID!): Boolean!
  createCategory(input: NewCategory!): Category!
  updateCategory(id: ID!, input: UpdateCategoryInput!): Category!
  deleteCategory(id: ID!): Boolean!
  addIngredient(input: NewIngredient!): Ingredient!
  deleteIngredient(id: ID!): Boolean!
  addInventory(input: NewInventory!): Inventory!
  updateInventory(id: ID!, input: UpdateInventory!): Inventory!
  freezeInventory(id: ID!): Inventory!
  deleteInventory(id: ID!): Boolean!
  updateQuantity(id: ID!, input: UpdateQuantity!): Inventory!
  addPurchaseHistory(input: NewPurchaseHistory!): PurchaseHistory!
  updatePurchaseHistory(id: ID!, input: UpdatePurchaseHistory!): PurchaseHistory!
  deletePurchaseHistory(id: ID!): Boolean!
}
